language: python
os:
  - "linux"
python:
  - "3.6"
install:
  - pip install -r requirements.txt
before_script:
  - "export MPLBACKEND=Agg"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - sh ci/scripts/runAllModels.sh
